<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textBox</name>
   <tag></tag>
   <elementGuidId>97363982-0e4e-4cdc-9b2e-62d2b1b2025e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;fname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;fname&quot;]</value>
      <webElementGuid>2a3c16f6-271f-4e3e-a6e2-3179d916b09e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
