<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_header</name>
   <tag></tag>
   <elementGuidId>73d72971-c99c-46d1-8834-841054bbcc68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/h1</value>
      <webElementGuid>cd22ed53-34c8-4852-8456-83c8ed3155cc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
